modLoader="javafml"
loaderVersion="[42,)"
# The license for your mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license="GNU GPLv3"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/skyjay1/RPG-Gods/issues"

[[mods]]
    modId="rpggods"
    version="19.1.0"
    displayName="RPG Gods"
    credits=""
    authors="skyjay1"
    description='''Gods and goddesses galore'''
[[dependencies.rpggods]]
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"
